ignore:
  - src/PartSeg_measurements/_version.py
coverage:
  status:
    project:
      default: false
      library:
        target: auto
        paths: [ '!.*/_tests/.*' ]
        threshold: 0.1%
      tests:
        target: auto
        paths: [ '.*/_tests/.*' ]
        threshold: 0.1%
comment:
  require_changes: true  # if true: only post the PR comment if coverage changes
codecov:
  require_ci_to_pass: false
